### ISSUE TITLE
script is inserted before html

### ISSUE THREAD

**Issue by zam6ak** [jsreport/jsreport-client-html#1]
Is there a reason why the script that is automatically injected cannot be  inserted via script tag?

Currently it is being inserted before document even begins, throwing off validation, and in some cases causing layout issue. Most importantly, the script injected contains report data, which in my case is rather large, so rendering is slowed down (compared to plain html recipie for example)

A simple solution would be just to require including a script link in either head or at the bottom.
It would be template author's responsibility to do so.

Another option would be to use new asset helper with special name.

**Comment by pofider** [comment]
Are you sure you've posted the issue into the right repository?

Isn't this one the right? https://github.com/jsreport/jsreport-browser-client/

**Comment by zam6ak** [comment]
Apologies you are right.  Some of projects are similarly named :)
Can this issue be moved there or should I close and open new issue?

**Comment by pofider** [comment]
Don't know how to do it. Please just open new one.
